apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.argo.serviceAccount }}-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.argo.serviceAccount }}-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.argo.serviceAccount }}
    namespace: {{ .Release.Namespace }}
