{
 "title": "Network performance",
 "description": "Prometheus speedtest exporter",
 "tags": [
  "speedtest",
  "network",
  "infra"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "NODE",
    "label": "Node",
    "query": {
     "query": "label_values(speedtest_download_bits_per_second,node)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Upload speed",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(node) (speedtest_upload_bits_per_second{node=~\"$NODE\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Download speed",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(node) (speedtest_download_bits_per_second{node=~\"$NODE\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Ping",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(node) (speedtest_ping_latency_milliseconds{node=~\"$NODE\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Historical data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Speedtest",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "decbits" } },
     "targets": [
      {
       "expr": "sum(speedtest_download_bits_per_second) by (node)",
       "legendFormat": "Download ({{node}})"
      },
      {
       "expr": "sum(speedtest_upload_bits_per_second) by (node)",
       "legendFormat": "Upload ({{node}})"
      }
     ]
    },
    {
     "title": "Ping time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(speedtest_ping_latency_milliseconds) by (node)",
       "legendFormat": "Ping ({{node}})"
      }
     ]
    },
    {
     "title": "Jitter",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(sum_over_time(speedtest_jitter_latency_milliseconds[5m]) ) by (node) / sum(count_over_time(speedtest_jitter_latency_milliseconds[5m]))by (node)",
       "legendFormat": "Jitter ({{node}})"
      }
     ]
    }
   ]
  }
 ]
}