apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: kibana
spec:
  gatewayClassName: cloudflare
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: {{ .Values.kibana.ingress.domain | quote }}
      allowedRoutes:
        kinds:
          - kind: HTTPRoute
        namespaces:
          from: Same
