apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kibana
spec:
  parentRefs:
    - name: kibana
      group: gateway.networking.k8s.io
      kind: Gateway
      namespace: {{ .Release.Namespace }}
      sectionName: http
  hostnames:
    - "{{ .Values.kibana.ingress.domain }}"
  rules:
    - backendRefs:
        - name: monitoring-kibana-kb-http
          group: ''
          kind: Service
          port: 5601
          weight: 1	
      matches:	
        - path:	
            type: PathPrefix	
            value: /
