name: homelab-monitoring
apiVersion: v2
version: 0.1.0
description: A Helm chart for deploying homelab monitoring stack
type: application
appVersion: "1.0.0"
maintainers:
  - name: KarafrOrg
    email: karafra@karafra.net
keywords:
  - monitoring
  - prometheus
  - grafana
  - loki
  - homelab
dependencies:
  - name: tempo
    version: 1.24.1
    repository: https://grafana.github.io/helm-charts
  - name: object-buckets
    version: 0.1.0
    repository: https://karafrorg.github.io/object-buckets
